# Generated by Django 6.0.4 on 2026-04-14 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criacao', 'Criação'), ('edicao', 'Edição'), ('desativacao', 'Desativação'), ('encerramento', 'Encerramento'), ('reabertura', 'Reabertura'), ('movimentacao', 'Movimentação'), ('login', 'Login'), ('logout', 'Logout')], max_length=30)),
                ('modelo_afetado', models.CharField(max_length=100)),
                ('objeto_id', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao', models.TextField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoria',
                'verbose_name_plural': 'Registros de Auditoria',
                'ordering': ['-criado_em'],
            },
        ),
    ]
