# Generated by Django 6.0.4 on 2026-04-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroauditoria',
            name='acao',
            field=models.CharField(choices=[('criacao', 'Criação'), ('edicao', 'Edição'), ('desativacao', 'Desativação'), ('encerramento', 'Encerramento'), ('reabertura', 'Reabertura'), ('movimentacao', 'Movimentação'), ('login', 'Login'), ('logout', 'Logout'), ('exclusao', 'Exclusão')], max_length=30),
        ),
    ]
