# Generated by Django 6.0.4 on 2026-04-15 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anexochamado',
            name='nome_original',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='anexochamado',
            name='arquivo',
            field=models.FileField(upload_to='chamados/anexos/'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_atendimento', 'Em atendimento'), ('aguardando_usuario', 'Aguardando usuário'), ('encerrado', 'Encerrado')], default='aberto', max_length=30),
        ),
        migrations.CreateModel(
            name='AcaoChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acoes_chamado', to=settings.AUTH_USER_MODEL)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='chamados.chamado')),
            ],
            options={
                'verbose_name': 'Ação de Atendimento',
                'verbose_name_plural': 'Ações de Atendimento',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AnexoAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='chamados/acoes/')),
                ('nome_original', models.CharField(blank=True, max_length=255)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='chamados.acaochamado')),
            ],
            options={
                'verbose_name': 'Anexo de Ação',
                'verbose_name_plural': 'Anexos de Ação',
                'ordering': ['enviado_em'],
            },
        ),
    ]
