# Generated by Django 6.0.4 on 2026-04-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_anexochamado_nome_original_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_atendimento', 'Em Atendimento'), ('aguardando_usuario', 'Aguardando usuário'), ('encerrado', 'Encerrado')], default='aberto', max_length=30),
        ),
    ]
