# Generated by Django 6.0.4 on 2026-04-20 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0003_alter_chamado_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=20)),
                ('prazo_horas', models.PositiveIntegerField(help_text='Prazo em horas para atendimento do chamado.')),
                ('categoria', models.ForeignKey(blank=True, help_text='Deixe em branco para aplicar a regra a todas as categorias desta prioridade.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_sla', to='chamados.categoriachamado')),
            ],
            options={
                'verbose_name': 'Configuração de SLA',
                'verbose_name_plural': 'Configurações de SLA',
                'ordering': ['prioridade', 'categoria__nome'],
                'constraints': [models.UniqueConstraint(fields=('prioridade', 'categoria'), name='sla_unico_prioridade_categoria')],
            },
        ),
    ]
