# Generated by Django 6.0.4 on 2026-04-27 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0004_configuracaosla'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], help_text='Dia da semana (0=Segunda … 6=Domingo).', unique=True)),
                ('hora_inicio', models.TimeField(help_text='Horário de início do expediente.')),
                ('hora_fim', models.TimeField(help_text='Horário de fim do expediente.')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para indicar que não há expediente neste dia.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Expediente',
                'verbose_name_plural': 'Configurações de Expediente',
                'ordering': ['dia_semana'],
            },
        ),
        migrations.CreateModel(
            name='FeriadoDiaAtipico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data do feriado ou dia atípico.', unique=True)),
                ('descricao', models.CharField(help_text='Descrição do feriado ou evento.', max_length=255)),
                ('tipo', models.CharField(choices=[('feriado_nacional', 'Feriado nacional'), ('feriado_estadual', 'Feriado estadual'), ('feriado_municipal', 'Feriado municipal'), ('recesso', 'Recesso'), ('ponto_facultativo', 'Ponto facultativo'), ('manutencao', 'Manutenção interna'), ('dia_atipico_sem_expediente', 'Dia atípico sem expediente'), ('dia_atipico_com_expediente', 'Dia atípico com expediente especial')], max_length=40)),
                ('contabiliza_sla', models.BooleanField(default=False, help_text='Marque se o SLA deve ser contabilizado neste dia.')),
                ('hora_inicio_especial', models.TimeField(blank=True, help_text='Horário de início do expediente especial (apenas para dias atípicos com expediente).', null=True)),
                ('hora_fim_especial', models.TimeField(blank=True, help_text='Horário de fim do expediente especial (apenas para dias atípicos com expediente).', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, help_text='Usuário que cadastrou este registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feriados_cadastrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feriado / Dia Atípico',
                'verbose_name_plural': 'Feriados / Dias Atípicos',
                'ordering': ['-data'],
            },
        ),
    ]
