# Generated by Django 6.0.4 on 2026-04-27 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0005_configuracaoexpediente_feriadodiaatipico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoRecalculoSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vencimento_anterior', models.DateTimeField()),
                ('vencimento_novo', models.DateTimeField()),
                ('data_impactada', models.DateField(help_text='Data do feriado/dia atipico que causou o recalculo.')),
                ('motivo', models.CharField(max_length=255)),
                ('recalculado_em', models.DateTimeField(auto_now_add=True)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos_recalculo_sla', to='chamados.chamado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historico de Recalculo de SLA',
                'verbose_name_plural': 'Historicos de Recalculo de SLA',
                'ordering': ['-recalculado_em'],
            },
        ),
    ]
