# Generated by Django 6.0.4 on 2026-05-12 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0006_historicorecalculosla'),
        ('servidores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='servidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados', to='servidores.servidor', verbose_name='Servidor afetado'),
        ),
    ]
