# Generated by Django 6.0.4 on 2026-08-10 13:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0007_chamado_servidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
