# Generated by Django 6.0.4 on 2026-04-14 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número')),
                ('fornecedor', models.CharField(max_length=200)),
                ('data_emissao', models.DateField(verbose_name='Data de emissão')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor total')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='notas_fiscais/', verbose_name='Arquivo PDF')),
                ('arquivo_xml', models.FileField(blank=True, null=True, upload_to='notas_fiscais/', verbose_name='Arquivo XML')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
                'ordering': ['-data_emissao'],
            },
        ),
    ]
