# Generated by Django 6.0.4 on 2026-04-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_setor_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setor',
            name='foto',
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/fotos/'),
        ),
    ]
