# Generated by Django 6.0.4 on 2026-05-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_credencial_externa'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='force_password_change',
            field=models.BooleanField(default=False, verbose_name='Forçar troca de senha'),
        ),
    ]
