# Generated by Django 6.0.4 on 2026-04-13 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Equipamento',
                'verbose_name_plural': 'Tipos de Equipamento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=50, unique=True, verbose_name='Numero da etiqueta')),
                ('numero_serie', models.CharField(blank=True, max_length=150, null=True, verbose_name='Numero de serie')),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=150, null=True)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descricao')),
                ('status', models.CharField(choices=[('disponivel', 'Disponivel'), ('em_uso', 'Em uso'), ('em_manutencao', 'Em manutencao'), ('baixado', 'Baixado')], default='disponivel', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observacoes')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrimonios_criados', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrimonios', to='usuarios.setor')),
                ('usuario_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrimonios', to=settings.AUTH_USER_MODEL, verbose_name='Usuario atual')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrimonios', to='patrimonio.tipoequipamento', verbose_name='Tipo de equipamento')),
            ],
            options={
                'verbose_name': 'Patrimonio',
                'verbose_name_plural': 'Patrimonios',
                'ordering': ['etiqueta'],
                'permissions': [('can_manage_patrimonio', 'Pode cadastrar e editar patrimonio')],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoPatrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('atribuicao', 'Atribuicao a usuario'), ('devolucao', 'Devolucao'), ('manutencao', 'Envio para manutencao'), ('retorno', 'Retorno de manutencao'), ('baixa', 'Baixa'), ('transferencia', 'Transferencia de setor'), ('outro', 'Outro')], max_length=20)),
                ('status_anterior', models.CharField(blank=True, max_length=20, null=True)),
                ('status_novo', models.CharField(blank=True, max_length=20, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_registradas', to=settings.AUTH_USER_MODEL)),
                ('setor_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_saida', to='usuarios.setor')),
                ('setor_novo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_entrada', to='usuarios.setor')),
                ('usuario_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_saida', to=settings.AUTH_USER_MODEL)),
                ('usuario_novo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_entrada', to=settings.AUTH_USER_MODEL)),
                ('patrimonio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='patrimonio.patrimonio')),
            ],
            options={
                'verbose_name': 'Movimentacao',
                'verbose_name_plural': 'Movimentacoes',
                'ordering': ['-data'],
            },
        ),
    ]
