# Generated by Django 6.0.4 on 2026-04-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoequipamento',
            name='aceita_software',
            field=models.BooleanField(default=False),
        ),
    ]
