# Generated by Django 6.0.4 on 2026-04-14 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas_fiscais', '0001_initial'),
        ('patrimonio', '0002_tipoequipamento_aceita_software'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrimonio',
            name='nota_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrimonios', to='notas_fiscais.notafiscal', verbose_name='Nota fiscal'),
        ),
    ]
