# Generated by Django 6.0.4 on 2026-04-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0003_patrimonio_nota_fiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrimonio',
            name='hostname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hostname'),
        ),
    ]
