# Generated by Django 6.0.4 on 2026-05-22 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0004_patrimonio_hostname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputadorEspecificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_gb', models.PositiveIntegerField(blank=True, null=True, verbose_name='RAM (GB)')),
                ('sistema_operacional', models.CharField(blank=True, help_text='Ex: Windows 11 Pro, Ubuntu 22.04', max_length=100, null=True, verbose_name='Sistema Operacional')),
                ('endereco_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('endereco_mac', models.CharField(blank=True, help_text='Formato: XX:XX:XX:XX:XX:XX', max_length=17, null=True, unique=True, verbose_name='Endereço MAC')),
                ('processador', models.CharField(blank=True, help_text='Ex: Intel Core i7-12700K, AMD Ryzen 7 5800X', max_length=255, null=True, verbose_name='Processador')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('patrimonio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='especificacao_computador', to='patrimonio.patrimonio', verbose_name='Patrimônio')),
            ],
            options={
                'verbose_name': 'Especificação de Computador',
                'verbose_name_plural': 'Especificações de Computador',
                'ordering': ['-criado_em'],
            },
        ),
    ]
