# Generated by Django 6.0.4 on 2026-05-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0005_computadorespecificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='computadorespecificacao',
            name='hostname',
            field=models.CharField(blank=True, help_text='Nome da máquina na rede', max_length=100, null=True, verbose_name='Hostname'),
        ),
    ]
