# Generated by Django 6.0.4 on 2026-05-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0006_computadorespecificacao_hostname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigCartorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Cartório do 9º Ofício de Notas', max_length=200)),
                ('endereco', models.CharField(default='R. São Paulo, 1115 - Centro, Belo Horizonte - MG, 30170-131', max_length=300)),
                ('tabeliao', models.CharField(default='Walquíria Mara Graciano Machado Rabelo', max_length=200)),
                ('responsavel_tecnico', models.CharField(default='Flávio Quitite Ferreira', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Logo do cartório (recomendado: 200x100px)', null=True, upload_to='cartorio/')),
                ('telefone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Cartório',
                'verbose_name_plural': 'Configurações do Cartório',
            },
        ),
    ]
