# Generated by Django 6.0.4 on 2026-05-11 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chamados', '0006_historicorecalculosla'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('hostname', models.CharField(blank=True, max_length=100)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('sistema_operacional', models.CharField(blank=True, max_length=100)),
                ('funcao', models.CharField(blank=True, max_length=200)),
                ('tipo', models.CharField(choices=[('fisico', 'Físico'), ('virtual', 'Virtual'), ('cloud', 'Cloud')], default='virtual', max_length=20)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('manutencao', 'Em manutenção')], default='ativo', max_length=20)),
                ('localizacao', models.CharField(blank=True, max_length=200)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servidor',
                'verbose_name_plural': 'Servidores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MudancaServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('configuracao', 'Configuração'), ('atualizacao', 'Atualização de sistema'), ('instalacao', 'Instalação de software'), ('manutencao', 'Manutenção'), ('seguranca', 'Correção de segurança'), ('hardware', 'Troca de hardware'), ('outro', 'Outro')], default='configuracao', max_length=20)),
                ('descricao', models.TextField()),
                ('origem', models.CharField(choices=[('manual', 'Registro manual'), ('chamado', 'Via chamado')], default='manual', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mudancas_servidor', to=settings.AUTH_USER_MODEL)),
                ('chamado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mudancas_servidor', to='chamados.chamado')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mudancas', to='servidores.servidor')),
            ],
            options={
                'verbose_name': 'Mudança',
                'verbose_name_plural': 'Mudanças',
                'ordering': ['-criado_em'],
            },
        ),
    ]
