# Generated by Django 6.0.4 on 2026-04-14 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notas_fiscais', '0001_initial'),
        ('patrimonio', '0002_tipoequipamento_aceita_software'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('fabricante', models.CharField(blank=True, max_length=150, null=True)),
                ('versao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Versão')),
                ('tipo_licenca', models.CharField(choices=[('perpétua', 'Perpétua'), ('assinatura', 'Assinatura'), ('oem', 'OEM'), ('freeware', 'Freeware'), ('opensource', 'Open Source'), ('outro', 'Outro')], default='perpétua', max_length=20, verbose_name='Tipo de licença')),
                ('controlado', models.BooleanField(default=True, help_text='Inclui no relatório de conformidade', verbose_name='Controlado')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Software',
                'verbose_name_plural': 'Softwares',
                'ordering': ['nome'],
                'unique_together': {('nome', 'versao', 'fabricante')},
            },
        ),
        migrations.CreateModel(
            name='LicencaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_adquirida', models.PositiveIntegerField(verbose_name='Quantidade adquirida')),
                ('chave_licenca', models.TextField(blank=True, null=True, verbose_name='Chave / licença')),
                ('data_aquisicao', models.DateField(verbose_name='Data de aquisição')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de vencimento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licencas_criadas', to=settings.AUTH_USER_MODEL)),
                ('nota_fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licencas', to='notas_fiscais.notafiscal', verbose_name='Nota fiscal')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='licencas.software', verbose_name='Software')),
            ],
            options={
                'verbose_name': 'Contrato de Licença',
                'verbose_name_plural': 'Contratos de Licença',
                'ordering': ['-data_aquisicao'],
            },
        ),
        migrations.CreateModel(
            name='InstalacaoSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_instalacao', models.DateField(blank=True, null=True, verbose_name='Data de instalação')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Instalação ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('patrimonio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='softwares_instalados', to='patrimonio.patrimonio', verbose_name='Equipamento')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instalacoes_registradas', to=settings.AUTH_USER_MODEL)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instalacoes', to='licencas.software', verbose_name='Software')),
            ],
            options={
                'verbose_name': 'Instalação de Software',
                'verbose_name_plural': 'Instalações de Software',
                'ordering': ['software__nome'],
                'unique_together': {('software', 'patrimonio')},
            },
        ),
    ]
