# Generated by Django 6.0.4 on 2026-05-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencacontrato',
            name='quantidade_utilizada',
            field=models.PositiveIntegerField(default=0, help_text='Licenças marcadas como em uso sem vínculo a um computador específico', verbose_name='Qtd. utilizada (sem instalação)'),
        ),
    ]
